DROP TABLE City CASCADE;
DROP TABLE CountryCode CASCADE;
DROP TABLE Discipline CASCADE;
DROP TABLE EventActivity CASCADE;
DROP TABLE Event CASCADE;
DROP TABLE Athlete CASCADE;
DROP TABLE Medal CASCADE;
